In [5]:
# Dependencies and Setup
import pandas as pd
from pathlib import Path

# File to Load (Remember to Change These)
school_data_to_load = Path("schools_complete.csv")
student_data_to_load = Path("students_complete.csv")

In [6]:
# Read School and Student Data File and store into Pandas DataFrames
school_data = pd.read_csv(school_data_to_load)
student_data = pd.read_csv(student_data_to_load)

# Combine the data into a single dataset.  
school_data_complete = pd.merge(student_data, school_data, how="left", on=["school_name", "school_name"])
school_data_complete.head()

,Student ID,student_name,gender,grade,school_name,reading_score,math_score,School ID,type,size,budget
0,0,Paul Bradley,M,9th,Huang High School,66,79,0,District,2917,1910635
1,1,Victor Smith,M,12th,Huang High School,94,61,0,District,2917,1910635
2,2,Kevin Rodriguez,M,12th,Huang High School,90,60,0,District,2917,1910635
3,3,Dr. Richard Scott,M,12th,Huang High School,67,58,0,District,2917,1910635
4,4,Bonnie Ray,F,9th,Huang High School,97,84,0,District,2917,1910635

In [10]:
# Total number of unique schools
total_unique_schools = school_data_complete['school_name'].nunique()

# Total students
total_students = school_data_complete['student_name'].count()

# Total budget
total_budget = school_data_complete['budget'].unique().sum()

# Average math score
average_math_score = school_data_complete['math_score'].mean()

# Average reading score
average_reading_score = school_data_complete['reading_score'].mean()

# Percentage passing math
passing_math_percentage = (school_data_complete['math_score'] >= 70).sum() / total_students * 100

# Percentage passing reading
passing_reading_percentage = (school_data_complete['reading_score'] >= 70).sum() / total_students * 100

# Percentage overall passing
overall_passing_percentage = ((school_data_complete['math_score'] >= 70) & (school_data_complete['reading_score'] >= 70)).sum() / total_students * 100

# Create a DataFrame for the district's key metrics
district_summary_df = pd.DataFrame({
    'Total Schools': [total_unique_schools],
    'Total Students': [total_students],
    'Total Budget': [total_budget],
    'Average Math Score': [average_math_score],
    'Average Reading Score': [average_reading_score],
    '% Passing Math': [passing_math_percentage],
    '% Passing Reading': [passing_reading_percentage],
    '% Overall Passing': [overall_passing_percentage]
})

# Display the district summary DataFrame
print(district_summary_df)

   Total Schools  Total Students  Total Budget  Average Math Score  \
0             15           39170      24649428           78.985371

   Average Reading Score  % Passing Math  % Passing Reading  % Overall Passing
0               81.87784       74.980853          85.805463          65.172326

In [12]:

# Group the data by school name
school_group = school_data_complete.groupby('school_name')

# School type (assuming it's the same for each row in the group)
school_type = school_group['type'].first()

# Total students
total_students = school_group['student_name'].count()

# Total school budget (assuming it's the same for each row in the group)
total_school_budget = school_group['budget'].first()

# Per student budget
per_student_budget = total_school_budget / total_students

# Average math score
average_math_score = school_group['math_score'].mean()

# Average reading score
average_reading_score = school_group['reading_score'].mean()

# Percentage passing math
passing_math_percentage = (school_data_complete['math_score'] >= 70).sum() / total_students * 100

# Percentage passing reading
passing_reading_percentage = (school_data_complete['reading_score'] >= 70).sum() / total_students * 100

# Percentage overall passing
overall_passing_percentage = ((school_data_complete['math_score'] >= 70) & (school_data_complete['reading_score'] >= 70)).sum() / total_students * 100

# Create a DataFrame for the school summary metrics
school_summary_df = pd.DataFrame({
    'School Type': school_type,
    'Total Students': total_students,
    'Total School Budget': total_school_budget,
    'Per Student Budget': per_student_budget,
    'Average Math Score': average_math_score,
    'Average Reading Score': average_reading_score,
    '% Passing Math': passing_math_percentage,
    '% Passing Reading': passing_reading_percentage,
    '% Overall Passing': overall_passing_percentage
})

# Display the school summary DataFrame
print(school_summary_df)

                      School Type  Total Students  Total School Budget  \
school_name
Bailey High School       District            4976              3124928
Cabrera High School       Charter            1858              1081356
Figueroa High School     District            2949              1884411
Ford High School         District            2739              1763916
Griffin High School       Charter            1468               917500
Hernandez High School    District            4635              3022020
Holden High School        Charter             427               248087
Huang High School        District            2917              1910635
Johnson High School      District            4761              3094650
Pena High School          Charter             962               585858
Rodriguez High School    District            3999              2547363
Shelton High School       Charter            1761              1056600
Thomas High School        Charter            1635              1043130
Wilson High School        Charter            2283              1319574
Wright High School        Charter            1800              1049400

                       Per Student Budget  Average Math Score  \
school_name
Bailey High School                  628.0           77.048432
Cabrera High School                 582.0           83.061895
Figueroa High School                639.0           76.711767
Ford High School                    644.0           77.102592
Griffin High School                 625.0           83.351499
Hernandez High School               652.0           77.289752
Holden High School                  581.0           83.803279
Huang High School                   655.0           76.629414
Johnson High School                 650.0           77.072464
Pena High School                    609.0           83.839917
Rodriguez High School               637.0           76.842711
Shelton High School                 600.0           83.359455
Thomas High School                  638.0           83.418349
Wilson High School                  578.0           83.274201
Wright High School                  583.0           83.682222

                       Average Reading Score  % Passing Math  \
school_name
Bailey High School                 81.033963      590.233119
Cabrera High School                83.975780     1580.731970
Figueroa High School               81.158020      995.930824
Ford High School                   80.746258     1072.289157
Griffin High School                83.816757     2000.681199
Hernandez High School              80.934412      633.656958
Holden High School                 83.814988     6878.220141
Huang High School                  81.182722     1006.856359
Johnson High School                80.966394      616.887209
Pena High School                   84.044699     3053.014553
Rodriguez High School              80.744686      734.433608
Shelton High School                83.725724     1667.802385
Thomas High School                 83.848930     1796.330275
Wilson High School                 83.989488     1286.465177
Wright High School                 83.955000     1631.666667

                       % Passing Reading  % Overall Passing
school_name
Bailey High School            675.442122         513.022508
Cabrera High School          1808.934338        1373.950484
Figueroa High School         1139.708376         865.649373
Ford High School             1227.090179         932.018985
Griffin High School          2289.509537        1738.964578
Hernandez High School         725.134844         550.765912
Holden High School           7871.194379        5978.454333
Huang High School            1152.211176         875.145698
Johnson High School           705.944129         536.189876
Pena High School             3493.762994        2653.638254
Rodriguez High School         840.460115         638.359590
Shelton High School          1908.574673        1449.630892
Thomas High School           2055.657492        1561.345566
Wilson High School           1472.185721        1118.177836
Wright High School           1867.222222        1418.222222

In [13]:
# Sort the schools by % Overall Passing in descending order
top_schools = school_summary_df.sort_values(by='% Overall Passing', ascending=False)

# Display the top 5 rows
print(top_schools.head())

                    School Type  Total Students  Total School Budget  \
school_name
Holden High School      Charter             427               248087
Pena High School        Charter             962               585858
Griffin High School     Charter            1468               917500
Thomas High School      Charter            1635              1043130
Shelton High School     Charter            1761              1056600

                     Per Student Budget  Average Math Score  \
school_name
Holden High School                581.0           83.803279
Pena High School                  609.0           83.839917
Griffin High School               625.0           83.351499
Thomas High School                638.0           83.418349
Shelton High School               600.0           83.359455

                     Average Reading Score  % Passing Math  % Passing Reading  \
school_name
Holden High School               83.814988     6878.220141        7871.194379
Pena High School                 84.044699     3053.014553        3493.762994
Griffin High School              83.816757     2000.681199        2289.509537
Thomas High School               83.848930     1796.330275        2055.657492
Shelton High School              83.725724     1667.802385        1908.574673

                     % Overall Passing
school_name
Holden High School         5978.454333
Pena High School           2653.638254
Griffin High School        1738.964578
Thomas High School         1561.345566
Shelton High School        1449.630892

In [14]:
# Save the bottom schools in a DataFrame called "bottom_schools"
bottom_schools = school_summary_df.sort_values(by='% Overall Passing', ascending=True).head()

# Display the bottom_schools DataFrame
print(bottom_schools)

                      School Type  Total Students  Total School Budget  \
school_name
Bailey High School       District            4976              3124928
Johnson High School      District            4761              3094650
Hernandez High School    District            4635              3022020
Rodriguez High School    District            3999              2547363
Figueroa High School     District            2949              1884411

                       Per Student Budget  Average Math Score  \
school_name
Bailey High School                  628.0           77.048432
Johnson High School                 650.0           77.072464
Hernandez High School               652.0           77.289752
Rodriguez High School               637.0           76.842711
Figueroa High School                639.0           76.711767

                       Average Reading Score  % Passing Math  \
school_name
Bailey High School                 81.033963      590.233119
Johnson High School                80.966394      616.887209
Hernandez High School              80.934412      633.656958
Rodriguez High School              80.744686      734.433608
Figueroa High School               81.158020      995.930824

                       % Passing Reading  % Overall Passing
school_name
Bailey High School            675.442122         513.022508
Johnson High School           705.944129         536.189876
Hernandez High School         725.134844         550.765912
Rodriguez High School         840.460115         638.359590
Figueroa High School         1139.708376         865.649373

In [27]:
# Group the data by school and grade
grade_math_scores = school_data_complete.groupby(['school_name', 'grade'])['math_score'].mean()

# Create a DataFrame for average math scores by grade and school
math_scores_by_grade = pd.DataFrame(grade_math_scores).unstack(level=-1)

# Display the DataFrame
print(math_scores_by_grade)

                      math_score
grade                       10th       11th       12th        9th
school_name
Bailey High School     76.996772  77.515588  76.492218  77.083676
Cabrera High School    83.154506  82.765560  83.277487  83.094697
Figueroa High School   76.539974  76.884344  77.151369  76.403037
Ford High School       77.672316  76.918058  76.179963  77.361345
Griffin High School    84.229064  83.842105  83.356164  82.044010
Hernandez High School  77.337408  77.136029  77.186567  77.438495
Holden High School     83.429825  85.000000  82.855422  83.787402
Huang High School      75.908735  76.446602  77.225641  77.027251
Johnson High School    76.691117  77.491653  76.863248  77.187857
Pena High School       83.372000  84.328125  84.121547  83.625455
Rodriguez High School  76.612500  76.395626  77.690748  76.859966
Shelton High School    82.917411  83.383495  83.778976  83.420755
Thomas High School     83.087886  83.498795  83.497041  83.590022
Wilson High School     83.724422  83.195326  83.035794  83.085578
Wright High School     84.010288  83.836782  83.644986  83.264706

In [28]:
# Group the data by school and grade, calculate the average reading score
grade_reading_scores = school_data_complete.groupby(['school_name', 'grade'])['reading_score'].mean()

# Create a DataFrame for average reading scores by grade and school
reading_scores_by_grade = pd.DataFrame(grade_reading_scores).unstack(level=-1)

# Display the DataFrame
print(reading_scores_by_grade)

                      reading_score
grade                          10th       11th       12th        9th
school_name
Bailey High School        80.907183  80.945643  80.912451  81.303155
Cabrera High School       84.253219  83.788382  84.287958  83.676136
Figueroa High School      81.408912  80.640339  81.384863  81.198598
Ford High School          81.262712  80.403642  80.662338  80.632653
Griffin High School       83.706897  84.288089  84.013699  83.369193
Hernandez High School     80.660147  81.396140  80.857143  80.866860
Holden High School        83.324561  83.815534  84.698795  83.677165
Huang High School         81.512386  81.417476  80.305983  81.290284
Johnson High School       80.773431  80.616027  81.227564  81.260714
Pena High School          83.612000  84.335938  84.591160  83.807273
Rodriguez High School     80.629808  80.864811  80.376426  80.993127
Shelton High School       83.441964  84.373786  82.781671  84.122642
Thomas High School        84.254157  83.585542  83.831361  83.728850
Wilson High School        84.021452  83.764608  84.317673  83.939778
Wright High School        83.812757  84.156322  84.073171  83.833333

In [23]:
# Define spending bins and labels
spending_bins = [0, 585, 630, 645, 680]
labels = ["<$585", "$585-630", "$630-645", "$645-680"]

# Create a new column in the DataFrame to represent spending range
school_summary_df['Spending Ranges (Per Student)'] = pd.cut(school_summary_df['Per Student Budget'], bins=spending_bins, labels=labels, include_lowest=True)

# Calculate mean scores per spending range
spending_math_scores = school_summary_df.groupby(["Spending Ranges (Per Student)"])["Average Math Score"].mean()
spending_reading_scores = school_summary_df.groupby(["Spending Ranges (Per Student)"])["Average Reading Score"].mean()
spending_passing_math = school_summary_df.groupby(["Spending Ranges (Per Student)"])["% Passing Math"].mean()
spending_passing_reading = school_summary_df.groupby(["Spending Ranges (Per Student)"])["% Passing Reading"].mean()
overall_passing_spending = school_summary_df.groupby(["Spending Ranges (Per Student)"])["% Overall Passing"].mean()

# Create a DataFrame called spending_summary
spending_summary = pd.DataFrame({
    'Average Math Score': spending_math_scores,
    'Average Reading Score': spending_reading_scores,
    '% Passing Math': spending_passing_math,
    '% Passing Reading': spending_passing_reading,
    '% Overall Passing': overall_passing_spending
})

# Display the spending_summary DataFrame
print(spending_summary)

                               Average Math Score  Average Reading Score  \
Spending Ranges (Per Student)
<$585                                   83.455399              83.933814
$585-630                                81.899826              83.155286
$630-645                                78.518855              81.624473
$645-680                                76.997210              81.027843

                               % Passing Math  % Passing Reading  \
Spending Ranges (Per Student)
<$585                             2844.270989        3254.884165
$585-630                          1827.932814        2091.822332
$630-645                          1149.745966        1315.729041
$645-680                           752.466842         861.096716

                               % Overall Passing
Spending Ranges (Per Student)
<$585                                2472.201219
$585-630                             1588.814058
$630-645                              999.343378
$645-680                              654.033828

/var/folders/j4/l11xbzm977n54mqf87yt4drh0000gn/T/ipykernel_80684/1550806799.py:9: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  spending_math_scores = school_summary_df.groupby(["Spending Ranges (Per Student)"])["Average Math Score"].mean()
/var/folders/j4/l11xbzm977n54mqf87yt4drh0000gn/T/ipykernel_80684/1550806799.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  spending_reading_scores = school_summary_df.groupby(["Spending Ranges (Per Student)"])["Average Reading Score"].mean()
/var/folders/j4/l11xbzm977n54mqf87yt4drh0000gn/T/ipykernel_80684/1550806799.py:11: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  spending_passing_math = school_summary_df.groupby(["Spending Ranges (Per Student)"])["% Passing Math"].mean()
/var/folders/j4/l11xbzm977n54mqf87yt4drh0000gn/T/ipykernel_80684/1550806799.py:12: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  spending_passing_reading = school_summary_df.groupby(["Spending Ranges (Per Student)"])["% Passing Reading"].mean()
/var/folders/j4/l11xbzm977n54mqf87yt4drh0000gn/T/ipykernel_80684/1550806799.py:13: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  overall_passing_spending = school_summary_df.groupby(["Spending Ranges (Per Student)"])["% Overall Passing"].mean()

In [24]:
# Define spending bins and labels
size_bins = [0, 1000, 2000, 5000]
labels = ["Small (<1000)", "Medium (1000-2000)", "Large (2000-5000)"]

# Create a new column in the DataFrame to represent school size
school_summary_df['School Size'] = pd.cut(school_summary_df['Total Students'], bins=size_bins, labels=labels, include_lowest=True)

# Calculate mean scores per school size
size_math_scores = school_summary_df.groupby(['School Size'])['Average Math Score'].mean()
size_reading_scores = school_summary_df.groupby(['School Size'])['Average Reading Score'].mean()
size_passing_math = school_summary_df.groupby(['School Size'])['% Passing Math'].mean()
size_passing_reading = school_summary_df.groupby(['School Size'])['% Passing Reading'].mean()
overall_passing_size = school_summary_df.groupby(['School Size'])['% Overall Passing'].mean()

# Create a DataFrame called size_summary
per_school_summary = pd.DataFrame({
    'Average Math Score': size_math_scores,
    'Average Reading Score': size_reading_scores,
    '% Passing Math': size_passing_math,
    '% Passing Reading': size_passing_reading,
    '% Overall Passing': overall_passing_size
})

# Display the size_summary DataFrame
print(per_school_summary)

                    Average Math Score  Average Reading Score  % Passing Math  \
School Size
Small (<1000)                83.821598              83.929843     4965.617347
Medium (1000-2000)           83.374684              83.864438     1735.442499
Large (2000-5000)            77.746417              81.344493      867.094051

                    % Passing Reading  % Overall Passing
School Size
Small (<1000)             5682.478687        4316.046293
Medium (1000-2000)        1985.979653        1508.422748
Large (2000-5000)          992.272083         753.666222

/var/folders/j4/l11xbzm977n54mqf87yt4drh0000gn/T/ipykernel_80684/800800110.py:9: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  size_math_scores = school_summary_df.groupby(['School Size'])['Average Math Score'].mean()
/var/folders/j4/l11xbzm977n54mqf87yt4drh0000gn/T/ipykernel_80684/800800110.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  size_reading_scores = school_summary_df.groupby(['School Size'])['Average Reading Score'].mean()
/var/folders/j4/l11xbzm977n54mqf87yt4drh0000gn/T/ipykernel_80684/800800110.py:11: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  size_passing_math = school_summary_df.groupby(['School Size'])['% Passing Math'].mean()
/var/folders/j4/l11xbzm977n54mqf87yt4drh0000gn/T/ipykernel_80684/800800110.py:12: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  size_passing_reading = school_summary_df.groupby(['School Size'])['% Passing Reading'].mean()
/var/folders/j4/l11xbzm977n54mqf87yt4drh0000gn/T/ipykernel_80684/800800110.py:13: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  overall_passing_size = school_summary_df.groupby(['School Size'])['% Overall Passing'].mean()

In [26]:
# Calculate mean scores per school type
type_math_scores = school_summary_df.groupby(['School Type'])['Average Math Score'].mean()
type_reading_scores = school_summary_df.groupby(['School Type'])['Average Reading Score'].mean()
type_passing_math = school_summary_df.groupby(['School Type'])['% Passing Math'].mean()
type_passing_reading = school_summary_df.groupby(['School Type'])['% Passing Reading'].mean()
overall_passing_type = school_summary_df.groupby(['School Type'])['% Overall Passing'].mean()

# Create a DataFrame called type_summary
type_summary = pd.DataFrame({
    'Average Math Score': type_math_scores,
    'Average Reading Score': type_reading_scores,
    '% Passing Math': type_passing_math,
    '% Passing Reading': type_passing_reading,
    '% Overall Passing': overall_passing_type
})

# Display the type_summary DataFrame
print(type_summary)

             Average Math Score  Average Reading Score  % Passing Math  \
School Type
Charter               83.473852              83.896421     2486.864046
District              76.956733              80.966636      807.183891

             % Passing Reading  % Overall Passing
School Type
Charter            2845.880170        2161.548020
District            923.712992         701.593134